version: '3.8'

services:
  torimemo:
    build: .
    ports:
      - "80:8080"
    volumes:
      - torimemo_data:/app/data
      - ./logs:/app/logs
    environment:
      - PORT=8080
      - DB_PATH=/app/data/torimemo.db
      - LOG_LEVEL=WARN
      - ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Reverse proxy with SSL termination
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - torimemo
    restart: always

volumes:
  torimemo_data:
    driver: local